name: kw-cs-homepage CI/CD

on:
  push:
    branches:
#      - main       # main 브랜치에서 동작
#      - develop    # develop 브랜치에서 동작
    branches-ignore:
      - main  # main 브랜치는 제외 (직접 테스트 후 main으로 머지)

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      # 3. Fly.io CLI 설치
      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
        shell: bash

      # 4. PATH 업데이트
      - name: Update PATH for Flyctl
        run: echo "$HOME/.fly/bin" >> $GITHUB_PATH

      # 5. 의존성 설치 및 빌드
      - name: Install Dependencies and Build
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DB_URL }}
        run: |
          npm install
          npm run build

      # 6. Fly.io로 배포
      - name: Deploy to Fly.io
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DB_URL }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly deploy --remote-only